FROM docker.io/bitnami/spark:3.5.1

# modifying the bitnami image to start spark-connect in master
COPY ./conf/run-spark.sh /opt/bitnami/scripts/spark/run-spark.sh
CMD [ "/opt/bitnami/scripts/spark/run-spark.sh"  ]

# adding additional jars for delta lake
# https://github.com/bitnami/containers/blob/main/bitnami/spark/README.md#installing-additional-jars
USER root
RUN install_packages curl
USER 1001
RUN curl https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar --output /opt/bitnami/spark/jars/delta-spark_2.12-3.1.0.jar
RUN curl https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar --output /opt/bitnami/spark/jars/delta-storage-3.1.0.jar